In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [126]:
data = pd.read_csv("C:\\Users\\ncair\\Downloads\\Class Quiz Week3_1 (Responses) - Form Responses 1.csv")
proj = pd.read_csv("C:\\Users\\ncair\\Downloads\\Project (beginner) cohort 9 - Group.csv")

In [19]:
data = data.set_index("Name")

In [158]:
data['Name']

0                   Omotola David
1                    Gloria Davut
2           Chinyere angel ozioko
3             EKEH ARINZE SUCCESS
4      Dangana Hawakulu Abdullahi
5                 victor okey udo
6           Aisha Muhammed Gidado
7           DIKE ZITA CHINECHEREM
8                 adewumi ayomide
9             Mubarak Mohammed O.
10          Arinze-Uhuo Chimsimdi
11            Odey Augustine Adie
12                   Fatima Barwa
13                    Chiedu Elue
14            Amina Muhammad Abdu
15        Hussaina Muhammad Shehu
16                Olamide Kolade
17             Chukwudi Iwuchukwu
18         mazino dickson-amagada
19          Oloye Kudirat Adenike
20          olusegun oluwaseyitan
21    Mohammed Abdulrasheed Taiye
22         Zane Richards-Offohndu
23         Khalid Abdulhamid Zago
24              Jasmine Hamilton
25                  Hassana Onipe
26            Chiedu Clement Elue
Name: Name, dtype: object

In [130]:
for i in range(len(data["Score"])):
    data["Score"][i] = int(data["Score"][i].split()[0])

C:\Users\ncair\AppData\Local\Temp\ipykernel_7712\2569292797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Score"][i] = int(data["Score"][i].split()[0])

In [131]:
data["Timestamp"] = pd.to_datetime(data["Timestamp"])

In [132]:
data

,Timestamp,Score,Name,"A variable is created the moment you first assign a value to it, what are the correct ways of Creating Variables.",Which of the following are valid Python variable names:,"What is a correct syntax to output ""Hello World"" in Python?",Which operator can be used to compare two values?,"In Python 3, which functions are used to accept input from the user",Which of the following statements assigns the value 100 to the variable x in Python:,How do you create a variable with the floating number 2.8?,How do you create a variable with the numeric value 5?,What is the correct file extension for Python files?,Should you use the == operator to determine whether objects of type float are equal?,How do you insert COMMENTS in Python code?,"In Python, 'Hello', is the same as ""Hello""",What is the value of the expression 100 / 25?
0,2023-07-20 08:46:35,30,Omotola David,"kadhb = 203j, x = y = z = ""Orange"", q1 = int(""3"")",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Sure!, Go for it",#This is a comment,True,4
1,2023-07-20 08:47:11,30,Gloria Davut,"q1 = int(""3""), x = y = z = ""Orange"", kadhb = 203j",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Sure!, Go for it",#This is a comment,True,4
2,2023-07-20 08:48:09,18,Chinyere angel ozioko,kadhb = 203j,home_address,"print(""Hello World"")",< >,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Sure!, Go for it",//This is a comment,True,4
3,2023-07-20 08:48:12,22,EKEH ARINZE SUCCESS,kadhb = 203j,home_address,"print(""Hello World"")",==,input(),x = 100,x = float(2.8),Both the answers are correct,.py,"Sure!, Go for it",#This is a comment,True,4
4,2023-07-20 08:48:41,30,Dangana Hawakulu Abdullahi,"q1 = int(""3""), x = y = z = ""Orange"", kadhb = 203j",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Sure!, Go for it",#This is a comment,True,4
5,2023-07-20 08:48:59,20,victor okey udo,"kadhb = 203j, q1 = int(""3"")",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Nope, not a good idea",#This is a comment,True,4
6,2023-07-20 08:50:16,18,Aisha Muhammed Gidado,"kadhb = 203j, my var = str(3), q1 = int(""3"")",home_address,"print(""Hello World"")",< >,input(),x = 100,Both the other answer are correct,x = 5,.py,"Sure!, Go for it",#This is a comment,True,4
7,2023-07-20 08:52:11,20,DIKE ZITA CHINECHEREM,kadhb = 203j,home_address,"print(""Hello World"")",> <,input(),x = 100,x = float(2.8),Both the answers are correct,.py,"Sure!, Go for it",#This is a comment,True,4
8,2023-07-20 08:52:34,26,adewumi ayomide,"q1 = int(""3""), x = y = z = ""Orange"", kadhb = 203j",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Nope, not a good idea",#This is a comment,False,4
9,2023-07-20 08:53:33,14,Mubarak Mohammed O.,"x = y = z = ""Orange"", 2ndChar = ""Hello World"",...",ver1.3,"Print(""Hello World"")",=,input(),x = 100,Both the other answer are correct,x = 5,.py,"Sure!, Go for it",#This is a comment,True,4
10,2023-07-20 08:54:00,20,Arinze-Uhuo Chimsimdi,"kadhb = 203j, q1 = int(""3""), x = y = z = ""Orange""",ver1.3,"Print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,x = int(5),.py,"Sure!, Go for it",#This is a comment,False,4
11,2023-07-20 08:54:40,12,Odey Augustine Adie,"x = y = z = ""Orange""",ver1.3,"print(""Hello World"")",< >,input(),x = 100,x = float(2.8),x = 5,.py,"Sure!, Go for it",#This is a comment,False,x=4
12,2023-07-20 08:54:48,18,Fatima Barwa,"q1 = int(""3""), x = y = z = ""Orange""",home_address,"print(""Hello World"")",==,input(),x = 100,x = float(2.8),x = int(5),.py,"Sure!, Go for it",#This is a comment,True,4
13,2023-07-20 08:55:13,18,Chiedu Elue,"2ndChar = ""Hello World""",return,"print(""Hello World"")",==,input(),x = 100,x = 2.8,x = 5,.py,"Sure!, Go for it",#This is a comment,True,4
14,2023-07-20 08:55:44,30,Amina Muhammad Abdu,"q1 = int(""3""), kadhb = 203j, x = y = z = ""Orange""",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Sure!, Go for it",#This is a comment,True,4
15,2023-07-20 08:56:33,18,Hussaina Muhammad Shehu,"kadhb = 203j, q1 = int(""3""), 2ndChar = ""Hello ...",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Nope, not a good idea",#This is a comment,False,4
16,2023-07-20 08:57:47,22,Olamide Kolade,kadhb = 203j,home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Nope, not a good idea",#This is a comment,True,4
17,2023-07-20 08:58:11,30,Chukwudi Iwuchukwu,"q1 = int(""3""), kadhb = 203j, x = y = z = ""Orange""",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Sure!, Go for it",#This is a comment,True,4
18,2023-07-20 08:59:01,14,mazino dickson-amagada,"q1 = int(""3"")",4square,"Print(""Hello World"")",> <,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Nope, not a good idea",/*This is a comment*/,True,4
19,2023-07-20 09:00:29,14,Oloye Kudirat Adenike,"x = y = z = ""Orange""",return,"print(""Hello World"")",< >,input(),x = 100,Both the other answer are correct,Both the answers are correct,.pyt,"Nope, not a good idea",#This is a comment,True,4
20,2023-07-20 09:02:37,20,olusegun oluwaseyitan,"x = y = z = ""Orange""",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,x = int(5),.py,"Nope, not a good idea",#This is a comment,True,4
21,2023-07-20 09:08:56,20,Mohammed Abdulrasheed Taiye,"q1 = int(""3""), my var = str(3), kadhb = 203j, ...",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Nope, not a good idea",#This is a comment,True,50
22,2023-07-20 09:12:37,10,Zane Richards-Offohndu,my var = str(3),Route 66,"print(""Hello World"")",==,input(),x = 100,x = float(2.8),x = 5,.pyt,"Sure!, Go for it",//This is a comment,False,4
23,2023-07-20 09:44:21,16,Khalid Abdulhamid Zago,"my var = str(3), q1 = int(""3""), kadhb = 203j",home_address,"print(""Hello World"")",==,input(),x = 100,x = 2.8,x = 5,.py,"Nope, not a good idea",#This is a comment,True,4
24,2023-07-20 10:32:24,22,Jasmine Hamilton,"kadhb = 203j, 2ndChar = ""Hello World"", x = y =...",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Nope, not a good idea",#This is a comment,True,4
25,2023-07-21 08:43:13,30,Hassana Onipe,"x = y = z = ""Orange"", kadhb = 203j, q1 = int(""3"")",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Sure!, Go for it",#This is a comment,True,4
26,2023-07-24 09:46:26,30,Chiedu Clement Elue,"kadhb = 203j, x = y = z = ""Orange"", q1 = int(""3"")",home_address,"print(""Hello World"")",==,input(),x = 100,Both the other answer are correct,Both the answers are correct,.py,"Sure!, Go for it",#This is a comment,True,4